services:
  pg_master:
    image: postgres:16.1-alpine3.19
    container_name: pg_master
    ports:
      - "5432:5432"
    volumes:
      - pg_master_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - pg-network

  pg_replica_1:
    image: postgres:16.1-alpine3.19
    container_name: pg_replica_1
    ports:
      - "5433:5432"
    volumes:
      - pg_replica_1_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - pg-network

  pg_replica_2:
    image: postgres:16.1-alpine3.19
    container_name: pg_replica_2
    ports:
      - "5434:5432"
    volumes:
      - pg_replica_2_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - pg-network

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pg_admin_data:/var/lib/pgadmin
    networks:
      - pg-network

volumes:
  pg_master_data:
  pg_replica_1_data:
  pg_replica_2_data:
  pg_admin_data:

networks:
  pg-network:
    driver: bridge