version: '3.8'

services:
  postgres-1:
    image: postgres:14
    container_name: postgres-1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data

  postgres-2:
    image: postgres:14
    container_name: postgres-2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5433:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data

  postgres-3:
    image: postgres:14
    container_name: postgres-3
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: db3
    ports:
      - "5434:5432"
    volumes:
      - postgres3_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-1
      - postgres-2
      - postgres-3
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_1_data:
  postgres_2_data:
  postgres_3_data:
  pgadmin_data:
